# Generated by Django 4.2.5 on 2023-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_alter_accounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='genre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='mood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000021ADD880C20>', max_length=200),
        ),
    ]
