# Generated by Django 4.2.5 on 2023-09-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_profiles_genre_profiles_mood_alter_accounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='generated_lyrics',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001379C7C3C40>', max_length=200),
        ),
    ]
