# Generated by Django 4.2.5 on 2023-09-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0005_profiles_generated_lyrics_alter_accounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000226B1663C40>', max_length=200),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='generated_lyrics',
            field=models.CharField(blank=True, null=True),
        ),
    ]
