# Generated by Django 4.2.5 on 2023-09-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0006_alter_accounts_uid_alter_profiles_generated_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000211B08A3C40>', max_length=200),
        ),
    ]
