# Generated by Django 4.2.5 on 2023-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0007_alter_accounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='assets/audiofiles/'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000021266ED3C40>', max_length=200),
        ),
    ]
