# Generated by Django 4.2.5 on 2023-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0008_profiles_audio_file_alter_accounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001FCCA6C3C40>', max_length=200),
        ),
    ]
