# Generated by Django 4.2.5 on 2023-09-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_alter_accounts_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='angry',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='funny',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='movie',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='petname',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='smile',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='sport',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000002114B3C3C40>', max_length=200),
        ),
    ]
