# Generated by Django 4.2.5 on 2023-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0010_profiles_angry_profiles_funny_profiles_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001EFCB446DE0>', max_length=200),
        ),
    ]
