# Generated by Django 4.2.5 on 2023-09-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0013_alter_accounts_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000026023236DE0>', max_length=200),
        ),
    ]
