# Generated by Django 3.2.21 on 2023-09-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0017_auto_20230912_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000023716E9DE40>', max_length=200),
        ),
    ]
